// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDnoBujoREo4B696ogmUhO8-4cTM6J7lA',
    appId: '1:1056618340036:web:7a1d3215ef1c6df3a33391',
    messagingSenderId: '1056618340036',
    projectId: 'disasterrelief-system',
    authDomain: 'disasterrelief-system.firebaseapp.com',
    storageBucket: 'disasterrelief-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFgpaevCm7eR6-R2MN61vXRaZo73IMrqI',
    appId: '1:1056618340036:android:9ec04a003b194ecfa33391',
    messagingSenderId: '1056618340036',
    projectId: 'disasterrelief-system',
    storageBucket: 'disasterrelief-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2t9PUTV5NTxODQ8tVl21Z5x0DS7NKCEs',
    appId: '1:1056618340036:ios:7c7141c90fdd2e7ea33391',
    messagingSenderId: '1056618340036',
    projectId: 'disasterrelief-system',
    storageBucket: 'disasterrelief-system.firebasestorage.app',
    iosBundleId: 'com.example.disasterManagementSystem',
  );
}
